//! The C subset generated by Resin.
//!
//! Structural nodes carry translation units, functions, blocks, and control flow.
//! Leaf strings are already C syntax: type declarations, expressions, and local
//! operations. Printing needs no Resin types, instructions, or compiler state.

#[derive(Debug, Clone)]
pub struct Module {
    pub includes: Vec<String>,
    pub assertions: Vec<(String, String)>,
    pub declarations: String,
    pub data: Vec<Vec<u32>>,
    pub prototypes: Vec<String>,
    pub lifecycle: String,
    pub functions: Vec<Function>,
    pub entry: Function,
}

#[derive(Debug, Clone)]
pub struct Function {
    pub signature: String,
    pub body: Body,
}

#[derive(Debug, Clone)]
pub enum Body {
    Inline(String),
    Blocks {
        locals: String,
        entry: usize,
        blocks: Vec<Block>,
    },
}

#[derive(Debug, Clone)]
pub struct Block {
    pub label: usize,
    pub statements: String,
    pub exit: Exit,
}

#[derive(Debug, Clone)]
pub enum Exit {
    Return(String),
    Jump(Edge),
    Branch {
        condition: String,
        then: Edge,
        els: Edge,
    },
    Unreachable,
}

#[derive(Debug, Clone)]
pub struct Edge {
    pub target: usize,
    pub values: Vec<EdgeValue>,
}

#[derive(Debug, Clone)]
pub struct EdgeValue {
    pub ty: String,
    pub value: String,
    pub live: Option<String>,
}
