"""
resin.comp models tensor computational graphs and provides tools for building,
transforming, interpreting, and compiling them.
"""

__all__ = [
    "BatchedMatrixMultiplicationKernel",
    "BatchedMatrixMultiplicationTensor",
    "BinaryOperator",
    "BroadcastTensor",
    "CompactTensor",
    "ConstantTensor",
    "DType",
    "ElementwiseOperationKernel",
    "ElementwiseOperationTensor",
    "ExecutionPlan",
    "IndexTensor",
    "Interpreter",
    "Kernel",
    "Operator",
    "Pitch",
    "ReductionTensor",
    "ReshapeTensor",
    "Shape",
    "SqueezeTensor",
    "Storage",
    "Substitution",
    "Tensor",
    "TensorDict",
    "TensorDictType",
    "TensorFunction",
    "UnaryOperator",
    "VarTensor",
    "compute_storage",
    "differentiate_graph",
    "dtype_bytes",
    "grad",
    "plan_execution",
    "tensordict_type",
    "tensordict_type_instantiate",
]

from .gradient import (
    differentiate_graph,
    grad,
)
from .interp import (
    Interpreter,
)
from .planner import (
    BatchedMatrixMultiplicationKernel,
    ElementwiseOperationKernel,
    ExecutionPlan,
    Kernel,
    Storage,
    compute_storage,
    plan_execution,
)
from .tensor import (
    BatchedMatrixMultiplicationTensor,
    BinaryOperator,
    BroadcastTensor,
    CompactTensor,
    ConstantTensor,
    DType,
    ElementwiseOperationTensor,
    IndexTensor,
    Operator,
    VarTensor,
    Pitch,
    ReductionTensor,
    ReshapeTensor,
    Shape,
    SqueezeTensor,
    Substitution,
    Tensor,
    TensorFunction,
    UnaryOperator,
    dtype_bytes,
    TensorDict,
    tensordict_type_instantiate,
    tensordict_type,
    TensorDictType,
)
