#!/usr/bin/env bash

# Convenience wrapper around `uv run invoke`.
# `invoke` aka `PyInvoke` is a cross-platform Make alternative for Python.
# See `tasks.py` for more.

uv run --all-extras invoke "$@"
