[project]
name = "resin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
authors = [{ name = "Nikhil Idiculla", email = "nikhil.idiculla@gmail.com" }]
dependencies = [
    "msgpack>=1.1.2",
    "numpy>=2.4.2",
    "pytest>=9.0.2",
    "rich>=14.3.2",
    "ruff>=0.14.14",
    "wgpu>=0.29.0",
]

[build-system]
requires = ["uv_build>=0.9.14,<0.10.0"]
build-backend = "uv_build"

[tool.ruff.lint]
extend-select = [
    # unsorted dunder all
    "RUF022",

    # import-outside-top-level
    "PLC0415",
]
