[project]
name = "resin"
version = "0.1.0"
description = "Souls-like game"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"

[project.scripts]
resin-build = "resin:build"

[tool.ruff]

[tool.ruff.lint]
extend-select = [
    # sort __all__
    "RUF022",

    # forbid imports outside top-level
    "PLC0415",
]
