[package]
name = "resin-compiler"
version.workspace = true
edition = "2024"
publish = false

[dependencies]
resin-common = { workspace = true }
resin-cst = { workspace = true }
resin-ast = { workspace = true }
resin-hir = { workspace = true }
resin-lir = { workspace = true }
resin-lir-verifier = { workspace = true }
resin-codegen = { workspace = true }
resin-platform-toolchain = { workspace = true }
