class WgpuInterp:
    def __init__(self, program_msgpack: bytes) -> None: ...
    def run(self) -> None: ...
    def write_buffer(self, buffer_index: int, data: bytes) -> None: ...
    def read_buffer(self, buffer_index: int) -> bytes: ...
    def param_buffer_index(self, param_id: int) -> int: ...
    def copy_buffer_to_buffer(
        self, src_buffer_index: int, dst_buffer_index: int
    ) -> None: ...

def decode_wgpu_program_msgpack(program_msgpack: bytes) -> None: ...
def encode_wgpu_program_msgpack(program_msgpack: bytes) -> bytes: ...

__all__ = [
    "WgpuInterp",
    "decode_wgpu_program_msgpack",
    "encode_wgpu_program_msgpack",
]
