[package]
name = "resin-runtime"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
ash = { version = "0.38", default-features = false, features = ["loaded", "std"] }
glfw-sys = { version = "8", default-features = false, features = ["src-build", "vulkan", "x11", "wayland"] }
libc = "0.2"
png = "0.17"
