[package]
name = "resin-compile"
version = "0.1.0"
edition = "2021"

[dependencies]
resin-core = { path = "../resin-core" }
resin-dsl = { path = "../resin-dsl" }
resin-ir = { path = "../resin-ir" }
resin-jit-wgpu = { path = "../resin-jit-wgpu" }

[[example]]
name = "interp_add"
path = "examples/interp_add.rs"
