[project]
name = "zfw_core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Nikhil Idiculla", email = "nikhil.idiculla@gmail.com" }]
requires-python = ">=3.14"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.10,<0.10.0", "uv"]
build-backend = "uv_build"

[tool.uv.build-backend]
package-data = { "zfw_core" = ["bundled_data/**/*"] }
module-name = "zfw_core"
module-root = ""
