[package]
name = "resin-lsp"
version = "0.1.0"
edition = "2024"
description = "Language server for Resin"
repository = "https://github.com/tsnl/resin"

[dependencies]
resin = { path = ".." }
lsp-server = "0.7.9"
lsp-types = "0.97"
crossbeam-channel = "0.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "2"
