[package]
name = "resin-lir"
version.workspace = true
edition = "2024"
publish = false
license.workspace = true

[dependencies]
resin-common = { workspace = true }
resin-types = { workspace = true }
resin-source = { workspace = true }
resin-hir = { workspace = true }
resin-executor = { workspace = true }
sexpfmt = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
