[package]
name = "resin-gaussians"
version = "0.1.0"
edition = "2024"

[dependencies]
resin-core = { path = "../resin-core" }
resin-dsl = { path = "../resin-dsl" }
resin-macros = { path = "../resin-macros" }

[dev-dependencies]
resin-jit = { path = "../resin-jit", default-features = false, features = ["cpu"] }
