[package]
name = "resin-codegen"
version.workspace = true
edition = "2024"
publish = false
license.workspace = true

[dependencies]
resin-executor = { workspace = true }
resin-types = { workspace = true }
resin-source = { workspace = true }
resin-lir = { workspace = true }
rspirv = "0.13"
tempfile = { workspace = true }
serde_json = "1"

[dev-dependencies]
tokio = { workspace = true }
