//! Regression tests against MuJoCo CPU reference trajectories.
//!
//! The reference values are `data.xpos` from MuJoCo 3.10 (f64, z-up),
//! generated by `scripts/mujoco_reference.py` from the models in
//! `examples/mjcf/` — embedded here so the test needs no Python. The full
//! comparison workflow (any model, any horizon, deviation report) is
//! `examples/mujoco_compare.rs`; findings so far:
//!
//! - Matched timesteps, no constraints (free fall): agreement to f32
//!   rounding (~1e-5 m over a second).
//! - Joints (pendulum): both engines discretize at O(h) but differently —
//!   MuJoCo integrates exact joint coordinates, resin projects positions.
//!   The gap shrinks linearly with h: 38 mm over 1 s at h = 2 ms, 1.9 mm at
//!   h = 0.1 ms — same continuum limit, different step error.
//! - Contacts (ball drop): impact transients differ by design (soft
//!   contacts vs projection + restitution); rest states agree to
//!   sub-millimeter.

use crate::jit::CpuJit;
use crate::physics::Simulation;
use crate::physics::mjcf::load_str;

/// Step `model` and return the y-up position of body row 1, sampled every
/// `stride` frames.
fn rollout(model: &str, substeps: usize, samples: usize, stride: usize) -> Vec<[f32; 3]> {
    let mut loaded = load_str(model).expect("load");
    loaded.scene.substeps = substeps;
    let mut sim = Simulation::new(CpuJit, loaded.scene, 1);
    let mut out = Vec::new();
    for _ in 0..samples {
        for _ in 0..stride {
            sim.step().expect("step");
        }
        out.push(sim.positions(0)[1]);
    }
    out
}

fn assert_tracks(ours: &[[f32; 3]], mujoco_zup: &[[f32; 3]], tolerance: f32) {
    for (step, (got, mj)) in ours.iter().zip(mujoco_zup).enumerate() {
        let want = [mj[0], mj[2], -mj[1]]; // z-up → y-up
        let deviation =
            ((got[0] - want[0]).powi(2) + (got[1] - want[1]).powi(2) + (got[2] - want[2]).powi(2))
                .sqrt();
        assert!(
            deviation <= tolerance,
            "sample {step}: {got:?} vs mujoco {want:?} ({deviation} > {tolerance})"
        );
    }
}

#[test]
fn free_fall_tracks_mujoco_to_f32_precision() {
    let ours = rollout(
        include_str!("../../../examples/mjcf/free_fall.xml"),
        1,
        20,
        1,
    );
    // MuJoCo 3.10 xpos, 20 steps of dt = 0.002.
    let mujoco = [
        [0.5, 0.25, 1.999961],
        [0.5, 0.25, 1.999882],
        [0.5, 0.25, 1.999765],
        [0.5, 0.25, 1.999608],
        [0.5, 0.25, 1.999411],
        [0.5, 0.25, 1.999176],
        [0.5, 0.25, 1.998901],
        [0.5, 0.25, 1.998587],
        [0.5, 0.25, 1.998234],
        [0.5, 0.25, 1.997842],
        [0.5, 0.25, 1.99741],
        [0.5, 0.25, 1.996939],
        [0.5, 0.25, 1.996429],
        [0.5, 0.25, 1.99588],
        [0.5, 0.25, 1.995291],
        [0.5, 0.25, 1.994663],
        [0.5, 0.25, 1.993996],
        [0.5, 0.25, 1.99329],
        [0.5, 0.25, 1.992544],
        [0.5, 0.25, 1.99176],
    ];
    assert_tracks(&ours, &mujoco, 1e-5);
}

#[test]
fn pendulum_tracks_mujoco_within_discretization_error() {
    let ours = rollout(
        include_str!("../../../examples/mjcf/pendulum.xml"),
        4,
        10,
        10,
    );
    // MuJoCo 3.10 xpos, every 10th step of dt = 0.002 (0.2 s of swing).
    let mujoco = [
        [0.5999962, 0.0, 1.397857],
        [0.5999442, 0.0, 1.391818],
        [0.5997265, 0.0, 1.381886],
        [0.5991497, 0.0, 1.368069],
        [0.5979455, 0.0, 1.35039],
        [0.5957723, 0.0, 1.328899],
        [0.5922182, 0.0, 1.30368],
        [0.5868073, 0.0, 1.274871],
        [0.5790087, 0.0, 1.242682],
        [0.5682506, 0.0, 1.207409],
    ];
    // O(h) discretization difference over 0.2 s at h = 0.5 ms.
    assert_tracks(&ours, &mujoco, 2e-3);
}
