id = "resin"
name = "Resin"
version = "0.1.0"
schema_version = 1
authors = ["Nikhil Idiculla <nikhil.idiculla@gmail.com>"]
description = "Resin language support and language server"
repository = "https://github.com/tsnl/resin"

[grammars.resin]
repository = "https://github.com/tsnl/resin"
rev = "e0455c238e8096ca8a925d187f27dc2f6ba5a7bf"
path = "tree-sitter-resin"

[language_servers.resin-lsp]
name = "Resin Language Server"
languages = ["Resin"]

[language_servers.resin-lsp.language_ids]
Resin = "resin"
