id = "resin"
name = "Resin"
version = "0.1.0"
schema_version = 1
authors = ["Nikhil Idiculla <nikhil.idiculla@gmail.com>"]
description = "Resin language support and language server"
repository = "https://github.com/tsnl/resin"

[grammars.resin]
repository = "https://github.com/tsnl/resin"
rev = "08b574f73416f047456804b1efa9e85f8953f6a4"
path = "tree-sitter-resin"

[language_servers.resin-lsp]
name = "Resin Language Server"
languages = ["Resin"]

[language_servers.resin-lsp.language_ids]
Resin = "resin"
