use crate::vocab::{LiteralNumber, LiteralString};
use crate::{Span, Symbol};

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum TokenKind {
    Lid(Symbol),
    Uid(Symbol),
    Hole(Symbol),

    LiteralNumber(Box<LiteralNumber>),
    LiteralString(Box<LiteralString>),

    Indent,
    Dedent,
    Eol,

    KwDef,
    KwLet,
    KwIf,
    KwThen,
    KwElif,
    KwElse,
    KwMatch,
    KwU8,
    KwU16,
    KwU32,
    KwU64,
    KwI8,
    KwI16,
    KwI32,
    KwI64,
    KwF32,
    KwF64,
    KwBool,
    KwString,
    KwSymbol,
    KwUnit,
    KwFnUid,
    KwTrue,
    KwFalse,

    LParen,
    RParen,
    LSqBrk,
    RSqBrk,
    LCurly,
    RCurly,
    Dot,
    Comma,
    Quote,
    Colon,
    DblColon,
    Semicolon,
    Asterisk,
    Percent,
    FSlash,
    DblFSlash,
    Plus,
    Minus,
    LShift,
    RShift,
    LessThan,
    GreaterThan,
    LessThanEq,
    GreaterThanEq,
    Bang,
    NotEq,
    Eq,
    DblEq,
    ThinRtArrow,
    ThinLtArrow,
    ThickRtArrow,
    Pipe,
    Ampersand,
    DblPipe,
    DblAmpersand,
    Caret,
}

impl TokenKind {
    pub fn name(&self) -> &'static str {
        match self {
            Self::Lid(_) => "<Lid>",
            Self::Uid(_) => "<Uid>",
            Self::Hole(_) => "<Hole>",
            Self::LiteralNumber(_) => "<Number>",
            Self::LiteralString(_) => "<String>",
            Self::Indent => "indent",
            Self::Dedent => "dedent",
            Self::Eol => "newline",
            Self::KwDef => "`def`",
            Self::KwLet => "`let`",
            Self::KwIf => "`if`",
            Self::KwThen => "`then`",
            Self::KwElif => "`elif`",
            Self::KwElse => "`else`",
            Self::KwMatch => "`match`",
            Self::KwU8 => "`u8`",
            Self::KwU16 => "`u16`",
            Self::KwU32 => "`u32`",
            Self::KwU64 => "`u64`",
            Self::KwI8 => "`i8`",
            Self::KwI16 => "`i16`",
            Self::KwI32 => "`i32`",
            Self::KwI64 => "`i64`",
            Self::KwF32 => "`f32`",
            Self::KwF64 => "`f64`",
            Self::KwBool => "`bool`",
            Self::KwString => "`string`",
            Self::KwSymbol => "`symbol`",
            Self::KwUnit => "`unit`",
            Self::KwFnUid => "`Fn`",
            Self::KwTrue => "`true`",
            Self::KwFalse => "`false`",
            Self::LParen => "`(`",
            Self::RParen => "`)`",
            Self::LSqBrk => "`[`",
            Self::RSqBrk => "`]`",
            Self::LCurly => "`{`",
            Self::RCurly => "`}`",
            Self::Dot => "`.`",
            Self::Comma => "`,`",
            Self::Quote => "`'`",
            Self::Colon => "`:`",
            Self::DblColon => "`::`",
            Self::Semicolon => "`;`",
            Self::Asterisk => "`*`",
            Self::Percent => "`%`",
            Self::FSlash => "`/`",
            Self::DblFSlash => "`//`",
            Self::Plus => "`+`",
            Self::Minus => "`-`",
            Self::LShift => "`<<`",
            Self::RShift => "`>>`",
            Self::LessThan => "`<`",
            Self::GreaterThan => "`>`",
            Self::LessThanEq => "`<=`",
            Self::GreaterThanEq => "`>=`",
            Self::Bang => "`!`",
            Self::NotEq => "`!=`",
            Self::Eq => "`=`",
            Self::DblEq => "`==`",
            Self::ThinRtArrow => "`->`",
            Self::ThinLtArrow => "`<-`",
            Self::ThickRtArrow => "`=>`",
            Self::Pipe => "`|`",
            Self::Ampersand => "`&`",
            Self::DblPipe => "`||`",
            Self::DblAmpersand => "`&&`",
            Self::Caret => "`^`",
        }
    }
    pub fn builtin_name(&self) -> Option<&'static str> {
        match self {
            Self::KwU8 => Some("u8"),
            Self::KwU16 => Some("u16"),
            Self::KwU32 => Some("u32"),
            Self::KwU64 => Some("u64"),
            Self::KwI8 => Some("i8"),
            Self::KwI16 => Some("i16"),
            Self::KwI32 => Some("i32"),
            Self::KwI64 => Some("i64"),
            Self::KwF32 => Some("f32"),
            Self::KwF64 => Some("f64"),
            Self::KwBool => Some("bool"),
            Self::KwString => Some("string"),
            Self::KwSymbol => Some("symbol"),
            Self::KwUnit => Some("unit"),
            _ => None,
        }
    }
}

#[derive(Clone, Debug)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
}
